# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_bealuna_rus.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(981, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(981, 600))
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(963, 581))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 561))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dens_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dens_f.sizePolicy().hasHeightForWidth())
        self.dens_f.setSizePolicy(sizePolicy)
        self.dens_f.setMinimumSize(QtCore.QSize(50, 20))
        self.dens_f.setAlignment(QtCore.Qt.AlignCenter)
        self.dens_f.setObjectName("dens_f")
        self.gridLayout_2.addWidget(self.dens_f, 13, 2, 1, 2)
        self.mgo_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mgo_f.sizePolicy().hasHeightForWidth())
        self.mgo_f.setSizePolicy(sizePolicy)
        self.mgo_f.setMinimumSize(QtCore.QSize(50, 20))
        self.mgo_f.setAlignment(QtCore.Qt.AlignCenter)
        self.mgo_f.setObjectName("mgo_f")
        self.gridLayout_2.addWidget(self.mgo_f, 8, 2, 1, 2)
        self.sludge_l = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.sludge_l.setFont(font)
        self.sludge_l.setObjectName("sludge_l")
        self.gridLayout_2.addWidget(self.sludge_l, 11, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.hfo_l = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.hfo_l.setFont(font)
        self.hfo_l.setObjectName("hfo_l")
        self.gridLayout_2.addWidget(self.hfo_l, 7, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.A_ps_line = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A_ps_line.sizePolicy().hasHeightForWidth())
        self.A_ps_line.setSizePolicy(sizePolicy)
        self.A_ps_line.setMinimumSize(QtCore.QSize(50, 20))
        self.A_ps_line.setAlignment(QtCore.Qt.AlignCenter)
        self.A_ps_line.setObjectName("A_ps_line")
        self.gridLayout_2.addWidget(self.A_ps_line, 3, 0, 1, 1)
        self.ballast_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ballast_f.sizePolicy().hasHeightForWidth())
        self.ballast_f.setSizePolicy(sizePolicy)
        self.ballast_f.setMinimumSize(QtCore.QSize(50, 20))
        self.ballast_f.setAlignment(QtCore.Qt.AlignCenter)
        self.ballast_f.setObjectName("ballast_f")
        self.gridLayout_2.addWidget(self.ballast_f, 5, 2, 1, 2)
        self.fw_l = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.fw_l.setFont(font)
        self.fw_l.setObjectName("fw_l")
        self.gridLayout_2.addWidget(self.fw_l, 6, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.label_stores = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stores.sizePolicy().hasHeightForWidth())
        self.label_stores.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_stores.setFont(font)
        self.label_stores.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_stores.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_stores.setObjectName("label_stores")
        self.gridLayout_2.addWidget(self.label_stores, 4, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.lo_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lo_f.sizePolicy().hasHeightForWidth())
        self.lo_f.setSizePolicy(sizePolicy)
        self.lo_f.setMinimumSize(QtCore.QSize(50, 20))
        self.lo_f.setAlignment(QtCore.Qt.AlignCenter)
        self.lo_f.setObjectName("lo_f")
        self.gridLayout_2.addWidget(self.lo_f, 9, 2, 1, 2)
        self.ship_lbl = QtWidgets.QLabel(self.layoutWidget)
        self.ship_lbl.setText("")
        self.ship_lbl.setPixmap(QtGui.QPixmap("img/ship_rus.jpg"))
        self.ship_lbl.setScaledContents(True)
        self.ship_lbl.setObjectName("ship_lbl")
        self.gridLayout_2.addWidget(self.ship_lbl, 1, 1, 3, 2)
        self.drafts_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drafts_label.sizePolicy().hasHeightForWidth())
        self.drafts_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.drafts_label.setFont(font)
        self.drafts_label.setMidLineWidth(1)
        self.drafts_label.setObjectName("drafts_label")
        self.gridLayout_2.addWidget(self.drafts_label, 0, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.F_ss_line = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F_ss_line.sizePolicy().hasHeightForWidth())
        self.F_ss_line.setSizePolicy(sizePolicy)
        self.F_ss_line.setMinimumSize(QtCore.QSize(50, 20))
        self.F_ss_line.setAlignment(QtCore.Qt.AlignCenter)
        self.F_ss_line.setObjectName("F_ss_line")
        self.gridLayout_2.addWidget(self.F_ss_line, 1, 3, 1, 1)
        self.F_ps_line = QtWidgets.QLineEdit(self.layoutWidget)
        self.F_ps_line.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F_ps_line.sizePolicy().hasHeightForWidth())
        self.F_ps_line.setSizePolicy(sizePolicy)
        self.F_ps_line.setMinimumSize(QtCore.QSize(50, 20))
        self.F_ps_line.setAlignment(QtCore.Qt.AlignCenter)
        self.F_ps_line.setObjectName("F_ps_line")
        self.gridLayout_2.addWidget(self.F_ps_line, 1, 0, 1, 1)
        self.M_ss_line = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.M_ss_line.sizePolicy().hasHeightForWidth())
        self.M_ss_line.setSizePolicy(sizePolicy)
        self.M_ss_line.setMinimumSize(QtCore.QSize(50, 20))
        self.M_ss_line.setAlignment(QtCore.Qt.AlignCenter)
        self.M_ss_line.setObjectName("M_ss_line")
        self.gridLayout_2.addWidget(self.M_ss_line, 2, 3, 1, 1)
        self.hfo_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hfo_f.sizePolicy().hasHeightForWidth())
        self.hfo_f.setSizePolicy(sizePolicy)
        self.hfo_f.setMinimumSize(QtCore.QSize(50, 20))
        self.hfo_f.setAlignment(QtCore.Qt.AlignCenter)
        self.hfo_f.setObjectName("hfo_f")
        self.gridLayout_2.addWidget(self.hfo_f, 7, 2, 1, 2)
        self.slops_l = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.slops_l.setFont(font)
        self.slops_l.setObjectName("slops_l")
        self.gridLayout_2.addWidget(self.slops_l, 10, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.ballast_l = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.ballast_l.setFont(font)
        self.ballast_l.setObjectName("ballast_l")
        self.gridLayout_2.addWidget(self.ballast_l, 5, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.sludge_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sludge_f.sizePolicy().hasHeightForWidth())
        self.sludge_f.setSizePolicy(sizePolicy)
        self.sludge_f.setMinimumSize(QtCore.QSize(50, 20))
        self.sludge_f.setAlignment(QtCore.Qt.AlignCenter)
        self.sludge_f.setObjectName("sludge_f")
        self.gridLayout_2.addWidget(self.sludge_f, 11, 2, 1, 2)
        self.mgo_l = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mgo_l.sizePolicy().hasHeightForWidth())
        self.mgo_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.mgo_l.setFont(font)
        self.mgo_l.setObjectName("mgo_l")
        self.gridLayout_2.addWidget(self.mgo_l, 8, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.lo_l = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lo_l.setFont(font)
        self.lo_l.setObjectName("lo_l")
        self.gridLayout_2.addWidget(self.lo_l, 9, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.fw_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fw_f.sizePolicy().hasHeightForWidth())
        self.fw_f.setSizePolicy(sizePolicy)
        self.fw_f.setMinimumSize(QtCore.QSize(50, 20))
        self.fw_f.setAlignment(QtCore.Qt.AlignCenter)
        self.fw_f.setObjectName("fw_f")
        self.gridLayout_2.addWidget(self.fw_f, 6, 2, 1, 2)
        self.A_ss_line = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A_ss_line.sizePolicy().hasHeightForWidth())
        self.A_ss_line.setSizePolicy(sizePolicy)
        self.A_ss_line.setMinimumSize(QtCore.QSize(50, 20))
        self.A_ss_line.setAlignment(QtCore.Qt.AlignCenter)
        self.A_ss_line.setObjectName("A_ss_line")
        self.gridLayout_2.addWidget(self.A_ss_line, 3, 3, 1, 1)
        self.M_ps_line = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.M_ps_line.sizePolicy().hasHeightForWidth())
        self.M_ps_line.setSizePolicy(sizePolicy)
        self.M_ps_line.setMinimumSize(QtCore.QSize(50, 20))
        self.M_ps_line.setAlignment(QtCore.Qt.AlignCenter)
        self.M_ps_line.setObjectName("M_ps_line")
        self.gridLayout_2.addWidget(self.M_ps_line, 2, 0, 1, 1)
        self.slops_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slops_f.sizePolicy().hasHeightForWidth())
        self.slops_f.setSizePolicy(sizePolicy)
        self.slops_f.setMinimumSize(QtCore.QSize(50, 20))
        self.slops_f.setAlignment(QtCore.Qt.AlignCenter)
        self.slops_f.setObjectName("slops_f")
        self.gridLayout_2.addWidget(self.slops_f, 10, 2, 1, 2)
        self.other_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.other_f.sizePolicy().hasHeightForWidth())
        self.other_f.setSizePolicy(sizePolicy)
        self.other_f.setMinimumSize(QtCore.QSize(50, 20))
        self.other_f.setAlignment(QtCore.Qt.AlignCenter)
        self.other_f.setObjectName("other_f")
        self.gridLayout_2.addWidget(self.other_f, 12, 2, 1, 2)
        self.other_l = QtWidgets.QLabel(self.layoutWidget)
        self.other_l.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.other_l.setFont(font)
        self.other_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.other_l.setAutoFillBackground(False)
        self.other_l.setAlignment(QtCore.Qt.AlignCenter)
        self.other_l.setObjectName("other_l")
        self.gridLayout_2.addWidget(self.other_l, 12, 0, 1, 2)
        self.dens_l = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dens_l.sizePolicy().hasHeightForWidth())
        self.dens_l.setSizePolicy(sizePolicy)
        self.dens_l.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.dens_l.setFont(font)
        self.dens_l.setScaledContents(False)
        self.dens_l.setAlignment(QtCore.Qt.AlignCenter)
        self.dens_l.setWordWrap(False)
        self.dens_l.setOpenExternalLinks(False)
        self.dens_l.setObjectName("dens_l")
        self.gridLayout_2.addWidget(self.dens_l, 13, 0, 1, 2)
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(370, 10, 588, 561))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.main_menu = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_menu.sizePolicy().hasHeightForWidth())
        self.main_menu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.main_menu.setFont(font)
        self.main_menu.setObjectName("main_menu")
        self.horizontalLayout_3.addWidget(self.main_menu)
        self.clear = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.horizontalLayout_3.addWidget(self.clear)
        self.countBtn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.countBtn.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBtn.sizePolicy().hasHeightForWidth())
        self.countBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.countBtn.setFont(font)
        self.countBtn.setAutoDefault(True)
        self.countBtn.setDefault(True)
        self.countBtn.setFlat(False)
        self.countBtn.setObjectName("countBtn")
        self.horizontalLayout_3.addWidget(self.countBtn)
        self.export_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_2.sizePolicy().hasHeightForWidth())
        self.export_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.export_2.setFont(font)
        self.export_2.setObjectName("export_2")
        self.horizontalLayout_3.addWidget(self.export_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 4, 0, 1, 2)
        self.result_l = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.result_l.setFont(font)
        self.result_l.setObjectName("result_l")
        self.gridLayout_4.addWidget(self.result_l, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.result = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result.sizePolicy().hasHeightForWidth())
        self.result.setSizePolicy(sizePolicy)
        self.result.setMinimumSize(QtCore.QSize(150, 480))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setFrameShape(QtWidgets.QFrame.Box)
        self.result.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.result.setText("")
        self.result.setScaledContents(True)
        self.result.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.result.setObjectName("result")
        self.gridLayout_4.addWidget(self.result, 1, 1, 1, 1)
        self.result_lables = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_lables.sizePolicy().hasHeightForWidth())
        self.result_lables.setSizePolicy(sizePolicy)
        self.result_lables.setMinimumSize(QtCore.QSize(430, 473))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.result_lables.setFont(font)
        self.result_lables.setFrameShape(QtWidgets.QFrame.Box)
        self.result_lables.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.result_lables.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.result_lables.setObjectName("result_lables")
        self.gridLayout_4.addWidget(self.result_lables, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Draft survey HC Bea-Luna"))
        self.sludge_l.setText(_translate("Form", "Шлам:"))
        self.hfo_l.setText(_translate("Form", "Тяжелое топливо:"))
        self.A_ps_line.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Consolas\'; color:#6a8759;\">Applicable draft values only: 2 - 7.8</span></p></body></html>"))
        self.fw_l.setText(_translate("Form", "Пресная вода:"))
        self.label_stores.setText(_translate("Form", "Расходные апасы:"))
        self.drafts_label.setText(_translate("Form", "Осадки:"))
        self.F_ss_line.setToolTip(_translate("Form", "<html><head/><body><pre align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#2b2b2b;\"><span style=\" font-family:\'Consolas\'; color:#6a8759;\">Applicable draft values only: 2 - 7.8</span></pre></body></html>"))
        self.F_ps_line.setToolTip(_translate("Form", "<html><head/><body><pre align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#2b2b2b;\"><span style=\" font-family:\'Consolas\'; color:#6a8759;\">Applicable draft values only: 2 - 7.8</span></pre></body></html>"))
        self.M_ss_line.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Consolas\'; color:#000000;\">Applicable draft values only: 2 - 7.8</span></p></body></html>"))
        self.slops_l.setText(_translate("Form", "Судовые запасы:"))
        self.ballast_l.setText(_translate("Form", "Балласт:"))
        self.mgo_l.setText(_translate("Form", "Дизельное топливо:"))
        self.lo_l.setText(_translate("Form", "Масло:"))
        self.A_ss_line.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Consolas\'; color:#6a8759;\">Applicable draft values only: 2 - 7.8</span></p></body></html>"))
        self.M_ps_line.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-family:\'Consolas\'; color:#6a8759;\">Applicable draft values only: 2 - 7.8</span></p></body></html>"))
        self.other_l.setText(_translate("Form", "Другие запасы:"))
        self.dens_l.setText(_translate("Form", "Плотность воды:"))
        self.main_menu.setText(_translate("Form", "Главное\n"
"меню"))
        self.clear.setText(_translate("Form", "Очистить\n"
"формы"))
        self.countBtn.setText(_translate("Form", "Посчитать\n"
"водоизмещение"))
        self.export_2.setText(_translate("Form", "Сохранить \n"
"расчет"))
        self.result_l.setText(_translate("Form", "Расчет:"))
        self.result_lables.setText(_translate("Form", "Носовая, мидель и кормовая средние осадки, м:\n"
"Носовое отстояние марки, м:\n"
"Отстояние марки на мидделе, м:\n"
"Кормовое отстояние марки, м:\n"
"Дифферент по маркам, м:\n"
"Носовая поправка марки, м:\n"
"Поправка марки мидделя, м:\n"
"Кормовая поправка марки, м:\n"
"Носовая скорректированная марка, м:\n"
"Скорректированная марка на мидделе, м:\n"
"Носовая скорректированная марка, м:\n"
"Скорректированный дифферент, м:\n"
"Прогиб/выгиб:\n"
"Общая средняя осадка судна (MOMC), м:\n"
"Водоизмещение по MOMCу, т:\n"
"Тонн на см, т:\n"
"Продольный центр плавучести, м:\n"
"Первая поправка за дифферент, т:\n"
"Момент изменения дифферента по МОМСу:\n"
"Момент изменения дифферента + / -:\n"
"Разница моментов изменения дифферента: \n"
"Вторая поправка за дифферент, т:\n"
"Водоизмещение скорректированное за дифферент, т: \n"
"Константа, т:\n"
"\n"
"Водоизмещение итоговое, т:"))
