# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_anyvsl_eng.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 550)
        Form.setMinimumSize(QtCore.QSize(1000, 550))
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 981, 531))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setGeometry(QtCore.QRect(280, 10, 251, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 225, 151))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.dens_l = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dens_l.sizePolicy().hasHeightForWidth())
        self.dens_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.dens_l.setFont(font)
        self.dens_l.setObjectName("dens_l")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dens_l)
        self.dens_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dens_f.sizePolicy().hasHeightForWidth())
        self.dens_f.setSizePolicy(sizePolicy)
        self.dens_f.setAlignment(QtCore.Qt.AlignCenter)
        self.dens_f.setObjectName("dens_f")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dens_f)
        self.LBP_l = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBP_l.sizePolicy().hasHeightForWidth())
        self.LBP_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.LBP_l.setFont(font)
        self.LBP_l.setObjectName("LBP_l")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LBP_l)
        self.LBP_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LBP_f.sizePolicy().hasHeightForWidth())
        self.LBP_f.setSizePolicy(sizePolicy)
        self.LBP_f.setAlignment(QtCore.Qt.AlignCenter)
        self.LBP_f.setObjectName("LBP_f")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LBP_f)
        self.fwd_delta_l = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fwd_delta_l.sizePolicy().hasHeightForWidth())
        self.fwd_delta_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.fwd_delta_l.setFont(font)
        self.fwd_delta_l.setObjectName("fwd_delta_l")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.fwd_delta_l)
        self.fwd_delta_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fwd_delta_f.sizePolicy().hasHeightForWidth())
        self.fwd_delta_f.setSizePolicy(sizePolicy)
        self.fwd_delta_f.setAlignment(QtCore.Qt.AlignCenter)
        self.fwd_delta_f.setObjectName("fwd_delta_f")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fwd_delta_f)
        self.mid_delta_l = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_delta_l.sizePolicy().hasHeightForWidth())
        self.mid_delta_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.mid_delta_l.setFont(font)
        self.mid_delta_l.setObjectName("mid_delta_l")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.mid_delta_l)
        self.mid_delta_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mid_delta_f.sizePolicy().hasHeightForWidth())
        self.mid_delta_f.setSizePolicy(sizePolicy)
        self.mid_delta_f.setAlignment(QtCore.Qt.AlignCenter)
        self.mid_delta_f.setObjectName("mid_delta_f")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mid_delta_f)
        self.aft_delta_l = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aft_delta_l.sizePolicy().hasHeightForWidth())
        self.aft_delta_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.aft_delta_l.setFont(font)
        self.aft_delta_l.setObjectName("aft_delta_l")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.aft_delta_l)
        self.aft_delta_f = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aft_delta_f.sizePolicy().hasHeightForWidth())
        self.aft_delta_f.setSizePolicy(sizePolicy)
        self.aft_delta_f.setAlignment(QtCore.Qt.AlignCenter)
        self.aft_delta_f.setObjectName("aft_delta_f")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.aft_delta_f)
        self.ships_name = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ships_name.sizePolicy().hasHeightForWidth())
        self.ships_name.setSizePolicy(sizePolicy)
        self.ships_name.setAlignment(QtCore.Qt.AlignCenter)
        self.ships_name.setObjectName("ships_name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ships_name)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(20, 230, 241, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.disp_MOMC_l = QtWidgets.QLabel(self.frame_2)
        self.disp_MOMC_l.setGeometry(QtCore.QRect(20, -48, 94, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disp_MOMC_l.sizePolicy().hasHeightForWidth())
        self.disp_MOMC_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.disp_MOMC_l.setFont(font)
        self.disp_MOMC_l.setObjectName("disp_MOMC_l")
        self.disp_MOMC_ = QtWidgets.QLineEdit(self.frame_2)
        self.disp_MOMC_.setGeometry(QtCore.QRect(120, -48, 133, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.disp_MOMC_.sizePolicy().hasHeightForWidth())
        self.disp_MOMC_.setSizePolicy(sizePolicy)
        self.disp_MOMC_.setAlignment(QtCore.Qt.AlignCenter)
        self.disp_MOMC_.setObjectName("disp_MOMC_")
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 10, 221, 181))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.layoutWidget_3)
        self.formLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.displ_momc_l = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displ_momc_l.sizePolicy().hasHeightForWidth())
        self.displ_momc_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.displ_momc_l.setFont(font)
        self.displ_momc_l.setObjectName("displ_momc_l")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.displ_momc_l)
        self.displ_momc_f = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.displ_momc_f.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displ_momc_f.sizePolicy().hasHeightForWidth())
        self.displ_momc_f.setSizePolicy(sizePolicy)
        self.displ_momc_f.setAlignment(QtCore.Qt.AlignCenter)
        self.displ_momc_f.setObjectName("displ_momc_f")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.displ_momc_f)
        self.TPC_l = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TPC_l.sizePolicy().hasHeightForWidth())
        self.TPC_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.TPC_l.setFont(font)
        self.TPC_l.setObjectName("TPC_l")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.TPC_l)
        self.TPC_f = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.TPC_f.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TPC_f.sizePolicy().hasHeightForWidth())
        self.TPC_f.setSizePolicy(sizePolicy)
        self.TPC_f.setAlignment(QtCore.Qt.AlignCenter)
        self.TPC_f.setObjectName("TPC_f")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.TPC_f)
        self.LCF_l = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LCF_l.sizePolicy().hasHeightForWidth())
        self.LCF_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.LCF_l.setFont(font)
        self.LCF_l.setObjectName("LCF_l")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.LCF_l)
        self.LCF_f = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.LCF_f.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LCF_f.sizePolicy().hasHeightForWidth())
        self.LCF_f.setSizePolicy(sizePolicy)
        self.LCF_f.setAlignment(QtCore.Qt.AlignCenter)
        self.LCF_f.setObjectName("LCF_f")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LCF_f)
        self.MTC_l = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MTC_l.sizePolicy().hasHeightForWidth())
        self.MTC_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.MTC_l.setFont(font)
        self.MTC_l.setObjectName("MTC_l")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.MTC_l)
        self.MTC_f = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.MTC_f.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MTC_f.sizePolicy().hasHeightForWidth())
        self.MTC_f.setSizePolicy(sizePolicy)
        self.MTC_f.setAlignment(QtCore.Qt.AlignCenter)
        self.MTC_f.setObjectName("MTC_f")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.MTC_f)
        self.MTC_plus_l = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MTC_plus_l.sizePolicy().hasHeightForWidth())
        self.MTC_plus_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.MTC_plus_l.setFont(font)
        self.MTC_plus_l.setObjectName("MTC_plus_l")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.MTC_plus_l)
        self.MTC_plus_f = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.MTC_plus_f.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MTC_plus_f.sizePolicy().hasHeightForWidth())
        self.MTC_plus_f.setSizePolicy(sizePolicy)
        self.MTC_plus_f.setAlignment(QtCore.Qt.AlignCenter)
        self.MTC_plus_f.setObjectName("MTC_plus_f")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.MTC_plus_f)
        self.MTC_minus_l = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MTC_minus_l.sizePolicy().hasHeightForWidth())
        self.MTC_minus_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.MTC_minus_l.setFont(font)
        self.MTC_minus_l.setObjectName("MTC_minus_l")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.MTC_minus_l)
        self.MTC_minus_f = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.MTC_minus_f.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MTC_minus_f.sizePolicy().hasHeightForWidth())
        self.MTC_minus_f.setSizePolicy(sizePolicy)
        self.MTC_minus_f.setAlignment(QtCore.Qt.AlignCenter)
        self.MTC_minus_f.setObjectName("MTC_minus_f")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.MTC_minus_f)
        self.light_ship_l = QtWidgets.QLabel(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.light_ship_l.sizePolicy().hasHeightForWidth())
        self.light_ship_l.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.light_ship_l.setFont(font)
        self.light_ship_l.setObjectName("light_ship_l")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.light_ship_l)
        self.light_ship_f = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.light_ship_f.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.light_ship_f.sizePolicy().hasHeightForWidth())
        self.light_ship_f.setSizePolicy(sizePolicy)
        self.light_ship_f.setAlignment(QtCore.Qt.AlignCenter)
        self.light_ship_f.setObjectName("light_ship_f")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.light_ship_f)
        self.layoutWidget_5 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 10, 261, 201))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.M_ps_line = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.M_ps_line.setAlignment(QtCore.Qt.AlignCenter)
        self.M_ps_line.setObjectName("M_ps_line")
        self.gridLayout_3.addWidget(self.M_ps_line, 2, 0, 1, 1)
        self.ship_2 = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ship_2.sizePolicy().hasHeightForWidth())
        self.ship_2.setSizePolicy(sizePolicy)
        self.ship_2.setText("")
        self.ship_2.setPixmap(QtGui.QPixmap("img/ship_eng.jpg"))
        self.ship_2.setObjectName("ship_2")
        self.gridLayout_3.addWidget(self.ship_2, 1, 1, 3, 2)
        self.drafts_label = QtWidgets.QLabel(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drafts_label.sizePolicy().hasHeightForWidth())
        self.drafts_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.drafts_label.setFont(font)
        self.drafts_label.setMidLineWidth(1)
        self.drafts_label.setObjectName("drafts_label")
        self.gridLayout_3.addWidget(self.drafts_label, 0, 1, 1, 2, QtCore.Qt.AlignHCenter)
        self.F_ss_line = QtWidgets.QLineEdit(self.layoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.F_ss_line.sizePolicy().hasHeightForWidth())
        self.F_ss_line.setSizePolicy(sizePolicy)
        self.F_ss_line.setMinimumSize(QtCore.QSize(0, 0))
        self.F_ss_line.setAlignment(QtCore.Qt.AlignCenter)
        self.F_ss_line.setObjectName("F_ss_line")
        self.gridLayout_3.addWidget(self.F_ss_line, 1, 3, 1, 1)
        self.A_ss_line = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.A_ss_line.setAlignment(QtCore.Qt.AlignCenter)
        self.A_ss_line.setObjectName("A_ss_line")
        self.gridLayout_3.addWidget(self.A_ss_line, 3, 3, 1, 1)
        self.F_ps_line = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.F_ps_line.setAlignment(QtCore.Qt.AlignCenter)
        self.F_ps_line.setObjectName("F_ps_line")
        self.gridLayout_3.addWidget(self.F_ps_line, 1, 0, 1, 1)
        self.M_ss_line = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.M_ss_line.setAlignment(QtCore.Qt.AlignCenter)
        self.M_ss_line.setObjectName("M_ss_line")
        self.gridLayout_3.addWidget(self.M_ss_line, 2, 3, 1, 1)
        self.A_ps_line = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.A_ps_line.setAlignment(QtCore.Qt.AlignCenter)
        self.A_ps_line.setObjectName("A_ps_line")
        self.gridLayout_3.addWidget(self.A_ps_line, 3, 0, 1, 1)
        self.layoutWidget_6 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget_6.setGeometry(QtCore.QRect(540, 10, 441, 511))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.result_l = QtWidgets.QLabel(self.layoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.result_l.setFont(font)
        self.result_l.setObjectName("result_l")
        self.gridLayout_4.addWidget(self.result_l, 0, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.result_lables = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_lables.sizePolicy().hasHeightForWidth())
        self.result_lables.setSizePolicy(sizePolicy)
        self.result_lables.setMinimumSize(QtCore.QSize(0, 480))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.result_lables.setFont(font)
        self.result_lables.setFrameShape(QtWidgets.QFrame.Box)
        self.result_lables.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.result_lables.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.result_lables.setObjectName("result_lables")
        self.gridLayout_4.addWidget(self.result_lables, 1, 0, 1, 1)
        self.result_anyvsl = QtWidgets.QLabel(self.layoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_anyvsl.sizePolicy().hasHeightForWidth())
        self.result_anyvsl.setSizePolicy(sizePolicy)
        self.result_anyvsl.setMinimumSize(QtCore.QSize(200, 480))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.result_anyvsl.setFont(font)
        self.result_anyvsl.setFrameShape(QtWidgets.QFrame.Box)
        self.result_anyvsl.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.result_anyvsl.setText("")
        self.result_anyvsl.setScaledContents(True)
        self.result_anyvsl.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.result_anyvsl.setObjectName("result_anyvsl")
        self.gridLayout_4.addWidget(self.result_anyvsl, 1, 1, 1, 1)
        self.main_menu = QtWidgets.QPushButton(self.frame_3)
        self.main_menu.setGeometry(QtCore.QRect(20, 460, 75, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_menu.sizePolicy().hasHeightForWidth())
        self.main_menu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.main_menu.setFont(font)
        self.main_menu.setObjectName("main_menu")
        self.clear = QtWidgets.QPushButton(self.frame_3)
        self.clear.setGeometry(QtCore.QRect(110, 460, 75, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.clear.setFont(font)
        self.clear.setObjectName("clear")
        self.export_2 = QtWidgets.QPushButton(self.frame_3)
        self.export_2.setEnabled(False)
        self.export_2.setGeometry(QtCore.QRect(440, 460, 76, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.export_2.sizePolicy().hasHeightForWidth())
        self.export_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.export_2.setFont(font)
        self.export_2.setObjectName("export_2")
        self.countBtn_momc = QtWidgets.QPushButton(self.frame_3)
        self.countBtn_momc.setGeometry(QtCore.QRect(200, 460, 93, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBtn_momc.sizePolicy().hasHeightForWidth())
        self.countBtn_momc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.countBtn_momc.setFont(font)
        self.countBtn_momc.setObjectName("countBtn_momc")
        self.countBtn_displ = QtWidgets.QPushButton(self.frame_3)
        self.countBtn_displ.setEnabled(False)
        self.countBtn_displ.setGeometry(QtCore.QRect(320, 460, 93, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countBtn_displ.sizePolicy().hasHeightForWidth())
        self.countBtn_displ.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.countBtn_displ.setFont(font)
        self.countBtn_displ.setObjectName("countBtn_displ")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(280, 190, 251, 251))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 221, 231))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10, 0, QtCore.Qt.AlignHCenter)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.ballast_l = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.ballast_l.setFont(font)
        self.ballast_l.setObjectName("ballast_l")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.ballast_l)
        self.ballast_f = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.ballast_f.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ballast_f.sizePolicy().hasHeightForWidth())
        self.ballast_f.setSizePolicy(sizePolicy)
        self.ballast_f.setAlignment(QtCore.Qt.AlignCenter)
        self.ballast_f.setObjectName("ballast_f")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ballast_f)
        self.fw_f = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.fw_f.setEnabled(False)
        self.fw_f.setAlignment(QtCore.Qt.AlignCenter)
        self.fw_f.setObjectName("fw_f")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fw_f)
        self.hfo_l = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.hfo_l.setFont(font)
        self.hfo_l.setObjectName("hfo_l")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.hfo_l)
        self.hfo_f = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.hfo_f.setEnabled(False)
        self.hfo_f.setAlignment(QtCore.Qt.AlignCenter)
        self.hfo_f.setObjectName("hfo_f")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.hfo_f)
        self.mgo_l = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.mgo_l.setFont(font)
        self.mgo_l.setObjectName("mgo_l")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.mgo_l)
        self.mgo_f = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.mgo_f.setEnabled(False)
        self.mgo_f.setAlignment(QtCore.Qt.AlignCenter)
        self.mgo_f.setObjectName("mgo_f")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mgo_f)
        self.lo_l = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lo_l.setFont(font)
        self.lo_l.setObjectName("lo_l")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lo_l)
        self.lo_f = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lo_f.setEnabled(False)
        self.lo_f.setAlignment(QtCore.Qt.AlignCenter)
        self.lo_f.setObjectName("lo_f")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lo_f)
        self.slops_l = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.slops_l.setFont(font)
        self.slops_l.setObjectName("slops_l")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.slops_l)
        self.slops_f = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.slops_f.setEnabled(False)
        self.slops_f.setAlignment(QtCore.Qt.AlignCenter)
        self.slops_f.setObjectName("slops_f")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.slops_f)
        self.sludge_l = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.sludge_l.setFont(font)
        self.sludge_l.setObjectName("sludge_l")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.sludge_l)
        self.sludge_f = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.sludge_f.setEnabled(False)
        self.sludge_f.setAlignment(QtCore.Qt.AlignCenter)
        self.sludge_f.setObjectName("sludge_f")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.sludge_f)
        self.other_l = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.other_l.setFont(font)
        self.other_l.setObjectName("other_l")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.other_l)
        self.other_f = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.other_f.setEnabled(False)
        self.other_f.setAlignment(QtCore.Qt.AlignCenter)
        self.other_f.setObjectName("other_f")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.other_f)
        self.fw_l = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.fw_l.setFont(font)
        self.fw_l.setObjectName("fw_l")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fw_l)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.F_ps_line, self.F_ss_line)
        Form.setTabOrder(self.F_ss_line, self.M_ps_line)
        Form.setTabOrder(self.M_ps_line, self.M_ss_line)
        Form.setTabOrder(self.M_ss_line, self.A_ps_line)
        Form.setTabOrder(self.A_ps_line, self.A_ss_line)
        Form.setTabOrder(self.A_ss_line, self.ships_name)
        Form.setTabOrder(self.ships_name, self.dens_f)
        Form.setTabOrder(self.dens_f, self.LBP_f)
        Form.setTabOrder(self.LBP_f, self.fwd_delta_f)
        Form.setTabOrder(self.fwd_delta_f, self.mid_delta_f)
        Form.setTabOrder(self.mid_delta_f, self.aft_delta_f)
        Form.setTabOrder(self.aft_delta_f, self.displ_momc_f)
        Form.setTabOrder(self.displ_momc_f, self.TPC_f)
        Form.setTabOrder(self.TPC_f, self.LCF_f)
        Form.setTabOrder(self.LCF_f, self.MTC_f)
        Form.setTabOrder(self.MTC_f, self.MTC_plus_f)
        Form.setTabOrder(self.MTC_plus_f, self.MTC_minus_f)
        Form.setTabOrder(self.MTC_minus_f, self.light_ship_f)
        Form.setTabOrder(self.light_ship_f, self.ballast_f)
        Form.setTabOrder(self.ballast_f, self.fw_f)
        Form.setTabOrder(self.fw_f, self.hfo_f)
        Form.setTabOrder(self.hfo_f, self.mgo_f)
        Form.setTabOrder(self.mgo_f, self.lo_f)
        Form.setTabOrder(self.lo_f, self.slops_f)
        Form.setTabOrder(self.slops_f, self.sludge_f)
        Form.setTabOrder(self.sludge_f, self.other_f)
        Form.setTabOrder(self.other_f, self.main_menu)
        Form.setTabOrder(self.main_menu, self.clear)
        Form.setTabOrder(self.clear, self.countBtn_momc)
        Form.setTabOrder(self.countBtn_momc, self.countBtn_displ)
        Form.setTabOrder(self.countBtn_displ, self.export_2)
        Form.setTabOrder(self.export_2, self.disp_MOMC_)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Draft survey custom vsl"))
        self.dens_l.setText(_translate("Form", "Water density:"))
        self.LBP_l.setText(_translate("Form", "LBP:"))
        self.fwd_delta_l.setText(_translate("Form", "Fwd delta:"))
        self.mid_delta_l.setText(_translate("Form", "Mid delta:"))
        self.aft_delta_l.setText(_translate("Form", "Aft delta:"))
        self.label.setText(_translate("Form", "Ship\'s name:"))
        self.disp_MOMC_l.setText(_translate("Form", "Displ. by MOMC:"))
        self.displ_momc_l.setText(_translate("Form", "Displ. by MOMC:"))
        self.TPC_l.setText(_translate("Form", "TPC:              "))
        self.LCF_l.setText(_translate("Form", "LCF:              "))
        self.MTC_l.setText(_translate("Form", "MTC:"))
        self.MTC_plus_l.setText(_translate("Form", "MTC +:"))
        self.MTC_minus_l.setText(_translate("Form", "MTC - :"))
        self.light_ship_l.setText(_translate("Form", "Light ship:"))
        self.drafts_label.setText(_translate("Form", "Drafts:"))
        self.result_l.setText(_translate("Form", "Results:"))
        self.result_lables.setText(_translate("Form", "Fwd, Mid, Aft mean draft, m:\n"
"Fwd mark misplacement, m:\n"
"Mid mark misplacement, m:\n"
"Aft mark misplacement, m:\n"
"Apparent trim, m:\n"
"Fwd draft correction, m:\n"
"Mid draft correction, m:\n"
"Aft draft correction, m:\n"
"Fwd corrected draft, m:\n"
"Mid corrected draft, m:\n"
"Aft corrected draft, m:\n"
"True trim, m:\n"
"Deflection:\n"
"Mean of means corrected, m:\n"
"Displacement by MOMC, mt:\n"
"TPC, mt:\n"
"LCF, m:\n"
"First trim correction, mt:\n"
"MTC by MOMC:\n"
"MTC + / -:\n"
"MTC difference:  \n"
"Second trim correction, mt:\n"
"Disp. corrected by trim, mt: \n"
"Constant, mt:\n"
"\n"
"Displacement corrected, mt:"))
        self.main_menu.setText(_translate("Form", "Main\n"
"menu"))
        self.clear.setText(_translate("Form", "Clear\n"
"forms"))
        self.export_2.setText(_translate("Form", "Export to \n"
"excel"))
        self.countBtn_momc.setText(_translate("Form", "Calculate\n"
"MOMC"))
        self.countBtn_displ.setText(_translate("Form", "Calculate\n"
"displacement"))
        self.label_10.setText(_translate("Form", "Consumables:"))
        self.ballast_l.setText(_translate("Form", "Ballast:"))
        self.hfo_l.setText(_translate("Form", "Heavy fuel:"))
        self.mgo_l.setText(_translate("Form", "Diesel oil:"))
        self.lo_l.setText(_translate("Form", "Lube oil:"))
        self.slops_l.setText(_translate("Form", "Slop stores:"))
        self.sludge_l.setText(_translate("Form", "Sludge:"))
        self.other_l.setText(_translate("Form", "Other:"))
        self.fw_l.setText(_translate("Form", "Fresh water:  "))
